[package]
name = "trellis"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
async-trait = "0.1"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.uuid]
version = "1"
features = ["v4"]